// project-templates/preact/script.jsx
import { h, render, Fragment } from 'preact';
import { useState } from 'preact/hooks';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="container">
      <h1>Preact App</h1>
      <p>A lightweight React alternative.</p>
      <div className="counter-display">{count}</div>
      <button className="accent-btn" onClick={() => setCount(count + 1)}>
        Increment
      </button>
    </div>
  );
}

render(<App />, document.getElementById('app'));

// test-solid/test-solid/script.jsx
import { render } from "solid-js/web";
import { createSignal } from "solid-js";

function Counter() {
  const [count, setCount] = createSignal(1);
  const increment = () => setCount(count => count + 1);
  console.log("This is a test");
  return (
    <button type="button" onClick={increment}>
      {count()}
    </button>
  );
}

render(() => <Counter />, document.getElementById("app"));
